USE WAREHOUSE GRAGEN_WH;
CREATE OR REPLACE ICEBERG TABLE GRAGEN_DB.GRAGEN.SAMPLE_PEDIGREE (
  SAMPLE_ID    STRING,
  FATHER_ID    STRING,
  MOTHER_ID    STRING,
  SEX          STRING,
  RELATIONSHIP STRING
)
EXTERNAL_VOLUME='GENOMICS_ICEBERG_VOLUME' ICEBERG_VERSION=2 CATALOG='SNOWFLAKE'
BASE_LOCATION='sample_pedigree/';

PUT file:///tmp/pedigree.csv @GRAGEN_DB.GRAGEN.GRAGEN_LOAD_STAGE OVERWRITE=TRUE AUTO_COMPRESS=TRUE;
COPY INTO GRAGEN_DB.GRAGEN.SAMPLE_PEDIGREE
  FROM @GRAGEN_DB.GRAGEN.GRAGEN_LOAD_STAGE/pedigree.csv
  FILE_FORMAT=(TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"' EMPTY_FIELD_AS_NULL=TRUE);

GRANT SELECT ON TABLE GRAGEN_DB.GRAGEN.SAMPLE_PEDIGREE TO ROLE PUBLIC;
GRANT SELECT ON TABLE GRAGEN_DB.GRAGEN.SAMPLE_PEDIGREE TO ROLE GRAGEN_DB_ROLE;

-- Verify a known CEU trio child (NA19828 has both parents) + count
SELECT * FROM GRAGEN_DB.GRAGEN.SAMPLE_PEDIGREE WHERE RELATIONSHIP='child' AND FATHER_ID IS NOT NULL AND MOTHER_ID IS NOT NULL LIMIT 3;
SELECT COUNT(*) AS total, COUNT(FATHER_ID) AS with_father, COUNT(MOTHER_ID) AS with_mother FROM GRAGEN_DB.GRAGEN.SAMPLE_PEDIGREE;
